sudo: false
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang

script:
 - echo hello | openssl dgst -sha512 | cut -d " " -f 2
 - locale && uname -a && dpkg -l
 - env
 - which java
 - java -version
 - which gcov
 - which gcovr
