sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
    - expat
    - fop
    - valgrind
    - xsltproc
#before_install:
#  - sudo apt-get update -qq
#  - dpkg -l 
script:
 - uname -a && dpkg -l
