version: 1.0.{build}

environment:
  matrix:
  # MSVC x32
  - name: win32
    platform: x86
    qt: 5.9\msvc2015
  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.9\msvc2015_64

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

build_script:
  - ps: |
      # be aware that vcvarsall will reset platform amd64 to X64!
      echo "platform: $env:platform"
      echo "qt: $env:qt"
      qmake -query
      Get-Location
      Write-Host "Finished build_script"

test_script:
  - ps: |
      $env:projdir=(C:\msys64\usr\bin\bash.exe -c "pwd")
      C:\msys64\usr\bin\bash.exe -lc "echo $env:projdir"
      Write-Host "Finished test_script with exit status $LastExitCode"

deploy_script:
  - ps: |
      $env:projdir=(C:\msys64\usr\bin\bash.exe -c "pwd")
      C:\msys64\usr\bin\bash.exe -lc "cd $env:projdir; ./ci_tokens"
      Write-Host "Finished deploy_script"

#deploy:
#  tag: 'continuous windows'
#  release: 'Continuous windows build'
#  description: 'Continuous build'
#  provider: GitHub
#  auth_token:
#    secure: gOkGevzhckv5gwFMhnyRk9JZqn6eaZ4vdVFkRdjL6p6NNZu7mwf8aTfMhWSnhaS2 # your encrypted token from GitHub
#  artifact: /GPSBabel.*Setup.exe/      # upload installer to release assets
#  draft: false
#  prerelease: true
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: false       # deploy on tag push only
#    platform: x86
#    qt: 5.9\msvc2015

skip_tags: true

